# Generated by Django 5.1.2 on 2024-11-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mentors/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('education', models.TextField(help_text='Educational background')),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
            ],
        ),
    ]
