# Generated by Django 5.1.2 on 2024-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='courses')),
                ('syllabus', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
