# Generated by Django 5.1.2 on 2024-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_type',
            field=models.CharField(default='Online - Self Learning', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
