# Generated by Django 5.1.2 on 2024-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0003_course_learning_type_course_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
