# Generated by Django 5.1.2 on 2024-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0004_alter_course_price_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Consultation fee', max_digits=10),
        ),
    ]
