# Generated by Django 5.1.2 on 2024-12-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='public_app.mentor'),
        ),
    ]
