# Generated by Django 5.1.2 on 2024-12-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
