# Generated by Django 5.1.2 on 2024-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0010_booking_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
